## <center>  <b> NLP Navigator - Assignment 1 </b>  </center>

This is the first assignment of the project and will test your basic python skills and what you have learnt so far about the libraries like numpy and matplotlib. The problem statement and your tasks are described below. You have to rename the notebook as `{Your Name}_Assignment1.ipynb` and write all the code and then generate outputs in it. Submission will be on github and more guidelines will be given soon. The deadline to submit the assignment is `10th June 5:00 PM`

Given a set of $ n $ points in $ d $ dimensional Euclidean Space, we will find all pairs of points whose Euclidean distance is less than $ r $.

Let  $ \overrightarrow{P_1} = (P_{11},P_{12}, \ldots, P_{1d}) $ and $ \overrightarrow{P_2} = (P_{21},P_{22}, \ldots, P_{2d}) $ be two points. Then the Euclidean distance between them is equal to the norm $ \left|\left| \overrightarrow{P_1} - \overrightarrow{P_2} \right|\right| $.

We have to find the set $ A = \left\{(i, j): \left|\left| \overrightarrow{P_1} - \overrightarrow{P_2} \right|\right| \leq r \right\} $ where $ i,j \in \{1,2,3,...,n\} $.


Obviously we can find it by using 2 nested loops and searching over all pairs, but we will do the task in an optimised way. Let us make a grid where each cell is of dimension $ r \times r $. Then, (say d = 2)

![graph1](https://drive.google.com/uc?export=view&id=1qIcPgkv9Q3fI-eV5AaAobjFIYy_2siZN)

Divide the points into the cells based on their coordinates. For example, say $ 4 $ points $ \left( \frac{1}{2}, \frac{2}{3} \right), \left( \frac{2}{3}, \frac{3}{2} \right), \left( 1, 1 \right), \left( \frac{3}{2}, \frac{5}{2} \right) $ and $ r = 1 $. So the division should be like -

![graph2](https://drive.google.com/uc?export=view&id=1-u-mT1PTxOkow_uz0T8ZBjU35u63uU7F)

Now comes the observation: For any point, the points which are within distance $ d $ from it must lie in 8 adjacent cells and no where else. So, for every point, just search the points present in 8 adjacent cells, and add the valid pairs to the answer set $ A $. Please note that for corner cells, the number of adjacent cells will not be equal to 8. So, write your code including those cases also.
##### Some points for higher dimension cases:
1. Think whether the number of adjacent cells for higher dimensions will be 8 or more (or less).
2. Observe that the dimension of each cell will not be $r*r$ for each case.
##### <u>Note</u>: Assume the pair $ (i,j) $ and $ (j,i) $ to be same. So write your code accordingly. For example, in 2-D space, we will count $ ((1,2), (4,5)) $ and $ ((4,5), (1,2)) $ only once.

## Tasks TO DO:

1. Generate a set of $ 1000 $ random points in $ 2 $ dimensional space with coordinates ranging between 0 and 100.
2. For $ r = \{ 1, 2, \ldots, 10 \} $, divide the points into grid as shown.
   - Show using matplotlib the various points using different colours.
   - Find pairs and store them in a list/set $ A $
3. Do task 1 and 2 for $ d = 3, 4, 10, 50, 100 $ (except plotting) and store the results.
(You can also plot for $ d = 3 $ but it is optional)

In [136]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [179]:
d=100
samplesize=1000
a = np.random.uniform(100,size=(samplesize,d))
a = a.round(2)
a

array([[97.46, 12.4 , 41.93, ..., 80.76, 19.18, 78.62],
       [64.7 , 52.79, 25.81, ..., 96.94, 17.13, 96.43],
       [27.87, 59.42, 48.54, ..., 37.74, 62.66, 61.13],
       ...,
       [18.91, 71.76, 37.84, ..., 59.16, 38.49, 94.96],
       [65.04, 35.35,  8.11, ...,  3.71, 85.41, 17.46],
       [89.57, 69.  , 42.48, ..., 92.6 , 26.05, 30.11]])

**the value of r can be changed from below**

In [180]:
df = pd.DataFrame(a)
r=10
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,97.46,12.40,41.93,78.18,74.23,1.77,54.68,13.01,81.26,99.53,...,43.80,76.92,59.55,55.86,58.34,43.77,78.09,80.76,19.18,78.62
1,64.70,52.79,25.81,12.57,62.38,55.15,76.75,25.99,92.27,44.27,...,93.23,99.98,85.29,81.34,7.42,32.70,53.54,96.94,17.13,96.43
2,27.87,59.42,48.54,81.52,23.18,42.03,31.30,65.00,88.81,53.60,...,73.34,24.49,51.64,66.06,54.41,2.24,5.30,37.74,62.66,61.13
3,30.62,11.72,44.55,15.37,65.12,62.89,89.78,30.23,28.60,18.05,...,34.12,64.23,48.38,46.90,20.84,37.21,35.89,97.98,21.60,18.21
4,2.15,1.62,39.30,60.50,22.31,14.90,80.85,11.97,41.10,62.74,...,28.98,1.35,76.41,44.50,72.11,61.86,72.78,58.71,48.68,80.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,65.00,37.13,66.58,35.02,41.44,90.82,42.11,20.69,62.80,76.90,...,21.65,5.69,74.48,67.27,78.93,87.19,78.41,74.68,31.19,15.31
996,35.42,51.43,99.49,41.15,88.25,98.20,22.98,21.37,43.64,81.37,...,17.90,66.80,3.96,84.56,83.13,62.53,13.47,94.07,28.95,13.33
997,18.91,71.76,37.84,55.20,83.99,80.64,93.17,54.35,40.74,87.98,...,17.54,59.46,9.76,88.62,20.62,26.58,57.04,59.16,38.49,94.96
998,65.04,35.35,8.11,99.30,96.71,28.53,2.26,81.04,77.55,60.40,...,4.09,35.47,63.31,70.70,56.53,19.75,9.41,3.71,85.41,17.46
999,89.57,69.00,42.48,46.52,13.26,57.92,4.97,43.02,91.12,41.63,...,59.89,75.19,52.10,85.67,83.26,62.92,93.03,92.60,26.05,30.11

In [181]:
def dist(i,j):
  sum = 0
  for k in range(d):
    sum = sum+((df.iloc[i,k]-df.iloc[j,k])**2)
  return sum

In [182]:
ans = [[df.iloc[0,:],df.iloc[0,:]]]

dfnew = df
for i in df.index:
  if(i%10==0):
    print(i/10)
  for j in range(d):
    k = df.iloc[i,j]
    dfnew = dfnew[((dfnew.iloc[:,j]-k)**2)<=(r**2)]
  for index in dfnew.index:
    if(((dist(i,index))<=(r**2))&(i!=index)):
      ans.append([df.iloc[i,:],df.iloc[index,:]])
  dfnew = df.iloc[i+1:]

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
24.0
25.0
26.0
27.0
28.0
29.0
30.0
31.0
32.0
33.0
34.0
35.0
36.0
37.0
38.0
39.0
40.0
41.0
42.0
43.0
44.0
45.0
46.0
47.0
48.0
49.0
50.0
51.0
52.0
53.0
54.0
55.0
56.0
57.0
58.0
59.0
60.0
61.0
62.0
63.0
64.0
65.0
66.0
67.0
68.0
69.0
70.0
71.0
72.0
73.0
74.0
75.0
76.0
77.0
78.0
79.0
80.0
81.0
82.0
83.0
84.0
85.0
86.0
87.0
88.0
89.0
90.0
91.0
92.0
93.0
94.0
95.0
96.0
97.0
98.0
99.0

In [183]:
ans

[[0     97.46
  1     12.40
  2     41.93
  3     78.18
  4     74.23
        ...
  95    43.77
  96    78.09
  97    80.76
  98    19.18
  99    78.62
  Name: 0, Length: 100, dtype: float64,
  0     97.46
  1     12.40
  2     41.93
  3     78.18
  4     74.23
        ...
  95    43.77
  96    78.09
  97    80.76
  98    19.18
  99    78.62
  Name: 0, Length: 100, dtype: float64]]